### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by 0xmcc** [xinnks/xns-seek-bar#4]
Hey, I don't know if this is a dumb question but I tried using this component via npm install, but I get the error

```
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <XnsSeekBar>
       <Footer> at src/components/Footer.vue
         <Player> at src/views/Player.vue
           <App> at src/App.vue
             <Root>
```

In Footer.vue (and main.js), I added - what am i doing wrong?

```
import XnsSeekBar from 'xns-seek-bar';
Vue.use(XnsSeekBar)
...
  components: {
   // ProgressBar,
    "xns-seek-bar": XnsSeekBar
    },
```

**Comment by xinnks** [comment]
@markocalvocruz  The plugin has already been imported into through Vue.use(), you don't need to re-initialize it through the components object, so remove this:
```js
components: {
   // ProgressBar,
    "xns-seek-bar": XnsSeekBar
},
```

**Comment by xinnks** [comment]
And there are no dumb questions, we learn through asking questions. @markocalvocruz

**Comment by xinnks** [comment]
And there are no dumb questions, we learn through asking questions. @markocalvocruz
